language: node_js
node_js:
  - "node"

before_install:
- npm i -g npm@latest

install:
- npm ci

after_script:
  - if [[ `node --version` == *v0.10* ]]; then cat ./coverage/lcov-report/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

addons:
  sauce_connect: true
